symbolicPath.1=gui/middleware
symbolicPath.2=gui/public
symbolicPath.3=gui/scheduler
symbolicPath.4=gui/Awareness
symbolicPath.5=gui/FileManager

symbolicPath.6=packages/middleware/pub
symbolicPath.23=packages/middleware/dependency/jars
symbolicPath.7=packages/Awareness/assistant
symbolicPath.8=packages/Awareness/dashboard
symbolicPath.9=packages/Awareness/examples
symbolicPath.10=packages/scheduler/cronJob
symbolicPath.11=packages/Wrapper/Authorization
symbolicPath.12=packages/Wrapper/AWS
symbolicPath.13=packages/Wrapper/Azure
symbolicPath.14=packages/Wrapper/docker
symbolicPath.15=packages/Wrapper/elasticsearch
symbolicPath.16=packages/Wrapper/mailchimp
symbolicPath.17=packages/syncloopai/adapter
symbolicPath.18=packages/syncloopai/assistant
symbolicPath.19=packages/syncloopai/dashboard
symbolicPath.20=packages/global/dependency/config/build
symbolicPath.21=packages/scheduler/dependency/jars
symbolicPath.22=packages/Awareness/dependency/jars
symbolicPath.24=packages/syncloopai/dependency/jars
symbolicPath.25=packages/FileManager/APIs
symbolicPath.26=packages/FileManager/dashboard
symbolicPath.27=packages/Awareness/mcp
symbolicPath.28=packages/middleware/mcp
symbolicPath.29=packages/scheduler/mcp
