#Properties saved at Thu Dec 04 14:41:24 UTC 2025
#Thu Dec 04 14:41:24 UTC 2025
basePath=http\://localhost\:8080
chatgptToken=sk-proj-j2vTHRkBZSWD4TsC6ThzT3BlbkFJK5JamQ5ZEEe39kovVQ4p
middleware.syncloop.gpt.assistant.apiservice.id=asst_Dn4909mu8BIQR2pqXQG6Kjfe
org.eka.middleware.service.startup=packages.middleware.pub.server.startUpServices.start.main,packages.middleware.pub.security.initOIDCProfiles.main
