google.clientId=323737830533-056jtrm82e6e5geikvag97a8j2ttej4v.apps.googleusercontent.com
google.secret=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
google.discoveryURI=https://accounts.google.com/.well-known/openid-configuration
google.useNonce=true
google.customParam.prompt=consent
google.basePath=http://localhost:9090

keycloak.clientId=Ekamw-keycloak-app
keycloak.secret=c1IMvzGIfLFtG6YX86QycJAGuqKIAfFb
keycloak.discoveryURI=http://localhost:8080/realms/EkamwAuth/.well-known/openid-configuration
keycloak.useNonce=true
keycloak.customParam.prompt=consent
keycloak.basePath=http://localhost:9090

okta.clientId=
okta.secret=
okta.discoveryURI=
okta.useNonce=true
okta.customParam.prompt=consent
okta.basePath=http://localhost:9090