clientId=0oa6gvdsa8UZtuZl35d7
secret=rHPM-JLOpDjFD6tzKxIjs8x9RZVMjDoqjEL9EVEc
discoveryURI=https://dev-60122436.okta.com/oauth2/aus6cpraytL7FjcTZ5d7/.well-known/oauth-authorization-server
useNonce=true
customParam.prompt=consent
preferredJwsAlgorithm=RS256
scope=groups openid